[package]
name = "splitar"
version = "0.1.0"
edition = "2021"
authors = ["(C) 2022 Ivan Boldyrev"]
description = "A tool for content-aware splitting of tar files"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.5", features = ["derive", "wrap_help"] }
env_logger = "0.9.0"
log = "0.4.14"
parse-size = { version = "1.0.0", features = ["std"] }
tar = "0.4.38"
termcolor = "1.1.1"
